### ISSUE TITLE
stars don't show up

### ISSUE THREAD

**Issue by zhangyongjiang** [kedardesai/KDRatingView#1]
It seems that in file KDRatingView.m line 28

UIImageView *starImageView = [[UIImageView alloc] initWithFrame:CGRectMake(xPos, self.frame.origin.y, self.frame.size.width/totalValue, self.frame.size.height)];

should be 

UIImageView *starImageView = [[UIImageView alloc] initWithFrame:CGRectMake(xPos, 0, self.frame.size.width/totalValue, self.frame.size.height)];

**Comment by kedardesai** [comment]
Thanks for your suggestion. I have made changes.
